### ISSUE TITLE
Help with Configuring a GitHub Page for a Videogame

### ISSUE THREAD

**Issue by MateoJimenezFamaArt** [MateoJimenezFamaArt/Hacktober_2024#1]
Heya

This repo is dedicated to search for help in configuring a github page for our teams newest videogame: Neurobound. 
We need help with setting up the page and uploading images.
🧑‍🎓 ❤️ 👨‍💻 👩‍💻 🫶 👾

**Comment by xaca** [comment]
@MateoJimenezFamaArt Hello, I could do it! 💪

**Comment by Soupmeme** [comment]
@MateoJimenezFamaArt Mondongo
