### ISSUE TITLE
I need help adding an Image to the Github page

### ISSUE THREAD

**Issue by MateoJimenezFamaArt** [MateoJimenezFamaArt/Hacktober_2024#4]
I need someone to please help me out by adding the game logo to the page and make it so the background is black and the letters become white. 

🙏 😄 👾

**Comment by xaca** [comment]
@MateoJimenezFamaArt I could explain you. It's easy, just put the assets in a folder called images in the root directory, then add html code for images. I will do it in a PR 📷
